# Generated by Django 3.2.6 on 2021-08-24 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template_info',
            fields=[
                ('upload_files', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Templates_info',
            },
        ),
    ]
