# Generated by Django 3.2.6 on 2021-09-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudStack_Instance_info',
            fields=[
                ('ins_id', models.TextField(primary_key=True, serialize=False)),
                ('user_id', models.TextField()),
                ('ins_name', models.TextField()),
                ('vol_id', models.TextField()),
                ('os_name', models.TextField()),
                ('created', models.TextField()),
            ],
            options={
                'db_table': 'snap_mig_service_cloudstack_instance_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OpenStack_Instance_info',
            fields=[
                ('ins_id', models.TextField(primary_key=True, serialize=False)),
                ('user_id', models.TextField()),
                ('ins_name', models.TextField()),
                ('vol_id', models.TextField()),
                ('os_name', models.TextField()),
                ('created', models.TextField()),
            ],
            options={
                'db_table': 'snap_mig_service_openstack_instance_info',
                'managed': False,
            },
        ),
    ]
