# Generated by Django 3.2.6 on 2021-09-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0002_cloudstack_instance_info_openstack_instance_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template_info',
            name='upload_files',
            field=models.CharField(max_length=500),
        ),
    ]
